apiVersion: v1
kind: Pod
metadata:
  name: pause
spec:
  containers:
  - name: pauseexample1
    imagePullPolicy: Always
    image: virtual-kubelet:3b9bfa47e839522bc19b6cb90156f733f645dca7600f292421f9657710498ac4
